---
# tasks file for cilium
- name: skip role if cilium is already installed
  ansible.builtin.meta: end_role
  when:
    - ansible_local.software.cilium.installed | default('false') | bool
    - not cilium_force_install | default(false) | bool
    - not cilium_upgrade | default(false) | bool

- name: import cilium variables specific to os distribution,family or version
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_version'] }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
        - "default.yml"
      paths:
        - "{{ role_path }}/vars"

- name: install cilium
  ansible.builtin.include_tasks: setup.yml
  when:
    - (cilium_supported | default(false) | bool) == true
    - not cilium_upgrade | default(false) | bool

- name: upgrade cilium
  ansible.builtin.import_tasks: upgrade.yml
  when:
    - ansible_local.software.cilium.installed | default('false') | bool
    - cilium_supported | default(false) | bool
    - cilium_upgrade | default(false) | bool
