---
- name: write cilium installed fact
  community.general.ini_file:
    path: "{{ cilium_path.fact_file }}"
    section: cilium
    option: installed
    value: "true"
    mode: '0644'

- name: write cilium version fact
  community.general.ini_file:
    path: "{{ cilium_path.fact_file }}"
    section: cilium
    option: version
    value: "{{ cilium_version }}"
    mode: '0644'

- name: refresh local facts
  ansible.builtin.setup:
    filter: ansible_local
