---
# tasks file for tailscale
- name: skip role if tailscale is already installed
  ansible.builtin.meta: end_role
  when:
    - (ansible_local.software.tailscale.installed | default('false') | bool) == true
    - (tailscale_force_install | default(false) | bool) != true

- name: import tailscale variables specific to os distribution,family or version
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_version'] }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
        - "default.yml"
      paths:
        - "{{ role_path }}/vars"

- name: install tailscale
  ansible.builtin.include_tasks: run.yml
  when:
    - (tailscale_supported | default(false) | bool) == true

