---
# debian-12 specific tasks
# - name: postinstall tasks for debian-12
#   when: ansible_facts['distribution_major_version'] == '12'
#   block:

# debian-13 specific tasks
# - name: postinstall tasks for debian-13
#   when: ansible_facts['distribution_major_version'] == '13'
#   block:

- name: set sysctls for tailscale
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "{{ tailscale_file_path.sysctl_file }}"
    state: present
    reload: true
  loop: "{{ tailscale_sysctl }}"

- name: disable upnp and portmapper for tailscale
  ansible.builtin.lineinfile:
    path: "{{ tailscale_file_path.env_file }}"
    regexp: '^{{ item.key }}='
    line: '{{ item.key }}={{ item.value }}'
    create: true
  loop:
    - { key: 'TS_DISABLE_UPNP', value: 'true' }
    - { key: 'TS_DISABLE_PORTMAPPER', value: 'true' }
  loop_control:
    label: "{{ item.key }}"
  when: tailscale_disable_upnp | default(true) | bool
  notify: restart tailscaled

- name: set tailscale config file using flags
  ansible.builtin.lineinfile:
    path: "{{ tailscale_file_path.env_file }}"
    regexp: '^FLAGS='
    line: 'FLAGS="--config={{ tailscale_file_path.config_file  }}"'
  notify: restart tailscaled

- name: create tailscale configuration directory
  ansible.builtin.file:
    path: "{{ tailscale_file_path.config_file | dirname }}"
    state: directory
    mode: '0755'

- name: prompt for tailscale auth key
  ansible.builtin.pause:
    prompt: "enter tailscale one-time auth key from https://console.tailscale.com/admin/settings/keys"
  register: tailscale_auth_key


- name: copy tailscale "{{ tailscale_file_path.config_file  }}"
  ansible.builtin.template:
    src: tailscale_config.json.j2
    dest: "{{ tailscale_file_path.config_file }}"
    mode: '0644'
  changed_when: true
  notify: restart tailscaled

# required if include_role is used instead of import_role
- name: flush handlers right now instead of waiting for the play to end
  ansible.builtin.meta: flush_handlers

- name: write tailscale installed fact
  community.general.ini_file:
    path: "{{ tailscale_file_path.ansible_fact }}"
    section: tailscale
    option: installed
    value: "true"
    mode: '0644'

- name: refresh local facts
  ansible.builtin.setup:
    filter: ansible_local
