---
# preinstall tasks for debian
- name: skip if debian version is not supported
  ansible.builtin.meta: end_host
  when: ansible_facts['distribution_major_version'] not in ['12', '13']

# debian-12 specific tasks
# - name: preinstall tasks for debian-12
#   when: ansible_facts['distribution_major_version']  == '12'
#   block:

# debian-13 specific tasks
# - name: preinstall tasks for debian-13
#   when: ansible_facts['distribution_major_version']  == '13'
#   block:

# - name: set sysctls for tailscale
#   ansible.posix.sysctl:
#     name: "{{ item.name }}"
#     value: "{{ item.value }}"
#     sysctl_file: "{{ tailscale_sysctl_file }}"
#     state: present
#     reload: true
#   loop: "{{ tailscale_sysctl }}"
