---

- name: check if there are any mounted partitions for storage device
  ansible.builtin.shell:
    cmd: lsblk -n -o NAME,MOUNTPOINT {{ storage_device }} | awk '$2 != "" {print $2}'
  register: storage_mounted_partitions
  when: storage_root_device_is_sdcard and (storage_device|default(''))|length > 0

- name: skip storage role if partitions are removed
  ansible.builtin.meta: end_host
  when: storage_mounted_partitions.stdout_lines | length > 0

