---
# detects if sdcard is root partition device
- name: check current source device for root partition
  ansible.builtin.command: findmnt -o source -n /
  register: storage_current_root_device
  changed_when: false

- name: check if sdcard is used for root partition
  ansible.builtin.set_fact:
    storage_root_device_is_sdcard: "{{ 'mmcblk' in storage_current_root_device.stdout }}"
  changed_when: false

