---
# tasks file for storage
- name: gather local facts
  ansible.builtin.setup:
    filter: ansible_local

- name: detect current root boot device
  import_tasks: detect_root.yml

# - name: end role if current root device is sdcard
#   ansible.builtin.meta: end_role
#   when: not storage_current_root_device_is_sdcard

# - import_tasks: detect_disk.yml

# - name: detect root storage device
#   import_tasks: detect_device.yml
#   when: storage_root_device_is_sdcard

- name: assert if there are mounted partitions on storage device
  import_tasks: assert_mounted_partitions.yml
  when: storage_root_device_is_sdcard

- name: partition storage device
  import_tasks: partition.yml
  when: storage_root_device_is_sdcard

- name: format partitions in storage device
  import_tasks: mkfs.yml
  when: storage_root_device_is_sdcard
