---
- name: set ownership of plex media directory
  ansible.builtin.file:
    path: "{{ plex_media_dir }}"
    owner: "{{ plex_media_dir_owner }}"
    group: "{{ plex_media_dir_group }}"
    state: directory
  when: plex_media_dir_ownership_set | default(false) == true

- name: set acl for plex media directory
  ansible.posix.acl:
    path: "{{ plex_media_dir }}"
    entity: "{{ item.entity }}"
    etype: "{{ item.etype }}"
    permissions: "{{ item.permissions }}"
    default: "{{ item.default | default(false) }}"
    state: present
  loop: "{{ plex_media_dir_acl }}"
  when: plex_media_dir_acl_set | default(false) == true
