---
- name: create temp file for plex signing key
  ansible.builtin.tempfile:
    state: file
    suffix: plexkey
  register: plex_key_tempfile

- name: download plex signing key
  ansible.builtin.get_url:
    url: "{{ plex_signing_key_url }}"
    dest: "{{ plex_key_tempfile.path }}"
    mode: '0644'
    force: true

- name: dearmor plex signing key
  ansible.builtin.command:
    cmd: gpg --yes --dearmor -o {{ plex_signing_key_path }} {{ plex_key_tempfile.path }}
  changed_when: true

- name: remove temp signing key
  ansible.builtin.file:
    path: "{{ plex_key_tempfile.path }}"
    state: absent

- name: add plex repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ plex_signing_key_path }}] https://repo.plex.tv/deb/ public main"
    state: present
    filename: "{{ plex_repo_file }}"

- name: install plex media server
  ansible.builtin.apt:
    name: plexmediaserver
    update_cache: true
    state: latest

- name: wait for plex to be ready
  ansible.builtin.pause:
    seconds: 10

- name: claim plex server
  when: plex_prompt_claim_token | default(true) == true
  block:
  - name: prompt for plex claim token
    ansible.builtin.pause:
      prompt: "enter plex claim token (valid for 4 minutes) from https://account.plex.tv/claim"
    register: plex_claim_token

  # NOTE: plex service does not use /etc/default/plexmediaserver
  # - name: ensure /etc/default/plexmediaserver exists
  #   ansible.builtin.file:
  #     path: /etc/default/plexmediaserver
  #     state: touch
  #     mode: '0644'
  #     owner: root
  #     group: root
  #     modification_time: preserve
  #     access_time: preserve

  # - name: set plex claim token
  #   ansible.builtin.lineinfile:
  #     path: /etc/default/plexmediaserver
  #     regexp: '^PLEX_CLAIM='
  #     line: 'PLEX_CLAIM={{ plex_claim_token.user_input }}'

  # - name: restart plex to apply claim
  #   ansible.builtin.service:
  #     name: plexmediaserver
  #     state: restarted

  - name: claim plex server (HTTP POST method)
    ansible.builtin.uri:
      url: "http://127.0.0.1:32400/myplex/claim?token={{ plex_claim_token.user_input }}"
      method: POST
      status_code: 200
    register: plex_claim_result
    retries: 5
    delay: 10
    until: plex_claim_result.status == 200
