---
# postinstall tasks
- name: common postinstall tasks
  block:
  - name: claim plex server
    when: (plex_prompt_claim_token | default(true) | bool) == true
    block:
    - name: prompt for plex claim token
      ansible.builtin.pause:
        prompt: "enter plex claim token (valid for 4 minutes) from https://account.plex.tv/claim"
      register: plex_claim_token
    - name: claim plex server (HTTP POST method)
      ansible.builtin.uri:
        url: "http://127.0.0.1:32400/myplex/claim?token={{ plex_claim_token.user_input }}"
        method: POST
        status_code: 200
      register: plex_claim_result
      retries: 5
      delay: 10
      until: plex_claim_result.status == 200

  - name: set ownership of plex media directory
    ansible.builtin.file:
      path: "{{ plex_media_dir }}"
      owner: "{{ plex_media_dir_owner }}"
      group: "{{ plex_media_dir_group }}"
      state: directory
    when: (plex_media_dir_ownership_set | default(false) | bool) == true
    tags: plex_postinstall_onwerership

  - name: set acl for plex media directory
    ansible.posix.acl:
      path: "{{ plex_media_dir }}"
      entity: "{{ item.entity }}"
      etype: "{{ item.etype }}"
      permissions: "{{ item.permissions }}"
      default: "{{ item.default | default(false) }}"
      state: present
    loop: "{{ plex_media_dir_acl }}"
    when: (plex_media_dir_acl_set | default(false) | bool) == true
    tags: plex_postinstall_acl

  - name: write plex installed ansible fact
    community.general.ini_file:
      path: "{{ plex_config_file_path.ansible_fact }}"
      section: plex
      option: installed
      value: "true"
      mode: '0644'

  - name: refresh local facts
    ansible.builtin.setup:
      filter: ansible_local
